### ISSUE TITLE
Mission Development Progress check

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Barter-Town#11]
The Repo hasn't been updated in a month. If this mission is still being worked on would you please update the repo with the local files. If not, I would ask for you to move this mission to your own account until a time when it will be actively worked on.

**Comment by WinterDesigns** [comment]
Its being developed on a active basis i hadnt had the time the past 3 weeks there will be a update probably within the next few days then testing should be good to roll.

**Comment by Jmaster9999** [comment]
This issue will be closed when noticeable progress has been made.

**Comment by Jmaster9999** [comment]
I haven't seen any progress being made, on THIS mission. If you don't do anything about this mission or show ScottyZ or myself what you have done to actually work on this mission within the next 4 days, this repo will be removed as abandoned. If there is a particular reason where you are not physically (too busy IRL,broken computer, etc) able to contribute regularly to this repo, talk to Scotty or myself.
