### ISSUE TITLE
Take a look at mission assets again and lets talk about usage.

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Barter-Town#3]
- All armored assets need to be removed. (Strykers, Bradleys and Abrams)
- All fixed wing aircraft need to be removed: (C-17s, F-18s, F-16s)

- Recommend removal of all ground vehicles excluding: MRAPs and Humvees.

Signed off by ScottyZ (Lead Mission Dev)

**Comment by WinterDesigns** [comment]
All light armored vics remain they are crucial to the success of the unit. (looking into adding PVs)

**Comment by coachwn** [comment]
Just because we are TF Red doesn't mean that we can't have armored vehicles in a mission. 

Also Winter with the fixed wing assets is it possible to assign them to the ALiVE tablet/laser designator in your mission for AI to handle those aircraft while we utilize the rotary wing assets on a player level?

**Comment by Scotty-Z** [comment]
the reason for removal of armor is the terrain and the fact that the 75th does not operate M1s or Bradley

**Comment by Scotty-Z** [comment]
@coachwn the same problem will arise that did with mine the fact that the AI plane will get stuck on the taxi way

**Comment by WinterDesigns** [comment]
75th does operate variants of the stryker icv which is known also i would have added this the aircraft to tablets but it was gonna be reliant on player operating them open for suggestions

**Comment by coachwn** [comment]
@Scotty-Z we can have the air coming in from off map that way they aren't sitting on the runway. I have to look at the wiki to sort out how that is done. It might not work on Clafghan due to pathing issues but that is what testing is for.

**Comment by WinterDesigns** [comment]
@coachwn air pathing is a nuisance on clafghan rapid changes looks extremely unrealistic better off using the arty and man portables

**Comment by WinterDesigns** [comment]
Just a advisory role before yall start asking for removal of vics might not be a terrible idea to talk to me first before pushing because you guys dont even know the backstory and or opord unless @coachwn has linked and provided . ground will not be permanently based out of the airfield .
