### ISSUE TITLE
Remake loadouts

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Barter-Town#4]
- Loadouts do not match anything that Rangers would deploy with. (Rangers do not use m1911s, or SMAWs)
- If you REALLY want to use SMAWs, you could make the unit semi-fictional (playing as TF-RED, a multi-branch taskforce)
- Switch to using the established standard loadout script system (found on github)

Signed off by ScottyZ (Lead Mission Dev)

**Comment by WinterDesigns** [comment]
1911s remain smaws shall be bansished from this world in place the swedes provail! Gustavs FOR EVERYONE!
