### ISSUE TITLE
Add VCOM AI.

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Barter-Town#5]
- All Missions for TF-Red must run the scripted version of VCOM AI (found [here:](https://www.dropbox.com/s/mi4ctubymyumefb/VcomAIScriptVersion2.81.zip?dl=0)
- You may also want to configure the AI to suit the deployment (difficulty, allowing them to call for cas,etc.)

Signed off by ScottyZ (Lead Mission Dev)

**Comment by coachwn** [comment]
Winter if you need help with the config on the server side AI I can work on that for you. Its relatively easy to setup and get moving correctly.

**Comment by WinterDesigns** [comment]
yea if you would be able im very appreciative.

**Comment by coachwn** [comment]
Will get to work on it tomorrow afternoon/evening my time.

**Comment by WinterDesigns** [comment]
Thank you

**Comment by WinterDesigns** [comment]
vcom is added to the mission as of now
