### ISSUE TITLE
Remove EODS

### ISSUE THREAD

**Issue by Jmaster9999** [Task-Force-Red/Operation-Barter-Town#7]
- EODS throws errors in the editor.
- EODS seems to throw errors while playing the mission.

- Some investigation is warranted to find out if the issues are fixable

Signed off by ScottyZ (Lead Mission Dev)

**Comment by coachwn** [comment]
Drop a link to the mod in here so I can take a look at it as well.

**Comment by WinterDesigns** [comment]
https://forums.bistudio.com/forums/topic/173102-eods-explosive-ordnance-disposal-suite/

some features were removed see how it works in testing

**Comment by WinterDesigns** [comment]
also appears to be the outdated version i was using by mistake probably will just remove it as a entity

**Comment by Scotty-Z** [comment]
just remove EODS it seems to still be buggy

**Comment by WinterDesigns** [comment]
already did eods hasnt been updated since mid last year from memory thats when this mission was initial started Resolved

**Comment by Jmaster9999** [comment]
Not resolved. EODS is still in the mission file
